# Generated by Django 4.2.4 on 2023-08-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('stock_room', models.CharField(choices=[('Albany', 'Albany'), ('Albert Street', 'Albert Street'), ('CBD East', 'CBD East'), ('CBD Other', 'CBD Other'), ('Henderson', 'Henderson'), ('Manukau', 'Manukau'), ('Takapuna/EkePanuku', 'Takapun/EkePanuku')], max_length=200)),
                ('allocated_to', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.category')),
            ],
        ),
    ]
