# Generated by Django 4.2.4 on 2023-08-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
