# Generated by Django 4.2.4 on 2023-08-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='stock_room',
            field=models.CharField(choices=[('Albany', 'Albany'), ('Albert Street', 'Albert Street'), ('CBD East', 'CBD East'), ('CBD Other', 'CBD Other'), ('Henderson', 'Henderson'), ('Manukau', 'Manukau'), ('Takapuna/EkePanuku', 'Takapun/EkePanuku'), ('TAU', 'TAU')], max_length=200),
        ),
    ]
