# Generated by Django 4.2.4 on 2023-08-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_items_allocated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='allocated_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
