# Generated by Django 4.2.4 on 2023-08-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_items_allocated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.location'),
            preserve_default=False,
        ),
    ]
